[package]
name = "msi-monitor-ctrl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
rusb = "0.9.4"
mlua = { version = "0.10.2", features = ["lua54", "vendored"] }
